language: python

python:
  - "3.6"
  # - "3.7"

install:
  - pip install pylint flake8
  - pip install .

script:
  - echo "*****Beginning pylint tests*****"
  # Disabling import-error for matplotlib/obspy errors, since we don't want to 
  # deal with installing them on travis.
  - pylint --disable=import-error bezpy
  - echo "*****Beginning flake8 tests*****"
  - flake8 bezpy